## Documentation: https://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx
  # - windows

julia:
  - 1.3
  - 1
  - nightly


notifications:
  email: false

env:
  # Disable test fuzzing for the moment, as we're a little too slow for Travis
  - NNLIB_TEST_FUZZING=false JULIA_NUM_THREADS=0
  - NNLIB_TEST_FUZZING=false JULIA_NUM_THREADS=2

# Submit to Codecov
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';


jobs:
  allow_failures:
    - julia: nightly
  # include: # no documentation yet
  #   - stage: "Documentation"
  #     julia: 1.3
  #     os: linux
  #     script:
  #       - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
  #                                   Pkg.instantiate()'
  #       - julia --project=docs/ docs/make.jl
  #     after_success: skip